        const fishDatabase = {
            angelfish: {
                commonName: "Freshwater Angelfish",
                scientificName: "Pterophyllum scalare",
                tempMin: 75,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 7.5,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 6,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "Group of 4-6",
                waterHardness: "5-13 dGH",
                lifespan: "8-10 years",
                careLevel: "Moderate"
            },
            pearlDanio: {
                commonName: "Pearl Danio",
                scientificName: "Danio albolineatus",
                tempMin: 68,
                tempMax: 77,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 7.5,
                tankSizeMin: 15,
                tankSizeUnit: "gallons",
                maxSize: 2.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "4-18 dGH",
                lifespan: "3-5 years",
                careLevel: "Easy"
            },
            neonTetra: {
                commonName: "Neon Tetra",
                scientificName: "Paracheirodon innesi",
                tempMin: 72,
                tempMax: 78,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.0,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 1.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "4-10 dGH",
                lifespan: "5-8 years",
                careLevel: "Easy"
            },
            celestialPearlDanio: {
                commonName: "Celestial Pearl Danio",
                scientificName: "Danio margaritatus",
                tempMin: 72,
                tempMax: 76,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 7.5,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 1,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 8-12",
                waterHardness: "5-12 dGH",
                lifespan: "3-5 years",
                careLevel: "Easy"
            },
            corydoras: {
                commonName: "Corydoras Catfish",
                scientificName: "Corydoras spp.",
                tempMin: 72,
                tempMax: 78,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 7.5,
                tankSizeMin: 15,
                tankSizeUnit: "gallons",
                maxSize: 2.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 6+",
                waterHardness: "5-15 dGH",
                lifespan: "5-10 years",
                careLevel: "Easy"
            },
            bettaFish: {
                commonName: "Betta Fish",
                scientificName: "Betta splendens",
                tempMin: 76,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 7.5,
                tankSizeMin: 5,
                tankSizeUnit: "gallons",
                maxSize: 3,
                sizeUnit: "inches",
                aggression: "Aggressive (males)",
                diet: "Carnivore",
                schooling: "Solitary",
                waterHardness: "5-15 dGH",
                lifespan: "3-5 years",
                careLevel: "Easy"
            },
            guppy: {
                commonName: "Guppy",
                scientificName: "Poecilia reticulata",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.8,
                phMax: 7.8,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 2,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 5+",
                waterHardness: "8-12 dGH",
                lifespan: "2-3 years",
                careLevel: "Very Easy"
            },
            molly: {
                commonName: "Molly",
                scientificName: "Poecilia sphenops",
                tempMin: 72,
                tempMax: 80,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 8.0,
                tankSizeMin: 15,
                tankSizeUnit: "gallons",
                maxSize: 4,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 4+",
                waterHardness: "10-25 dGH",
                lifespan: "3-5 years",
                careLevel: "Easy"
            },
            platy: {
                commonName: "Platy",
                scientificName: "Xiphophorus maculatus",
                tempMin: 68,
                tempMax: 79,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 8.2,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 2.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 3+",
                waterHardness: "10-25 dGH",
                lifespan: "3 years",
                careLevel: "Easy"
            },
            swordtail: {
                commonName: "Swordtail",
                scientificName: "Xiphophorus hellerii",
                tempMin: 64,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 8.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 5.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 5+",
                waterHardness: "12-18 dGH",
                lifespan: "4 years",
                careLevel: "Easy"
            },
            endlersLivebearer: {
                commonName: "Endler's Livebearer",
                scientificName: "Poecilia wingei",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 8.5,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 1.8,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 6+",
                waterHardness: "12-30 dGH",
                lifespan: "2-3 years",
                careLevel: "Very Easy"
            },
            whiteCloudMinnow: {
                commonName: "White Cloud Mountain Minnow",
                scientificName: "Tanichthys albonubes",
                tempMin: 57,
                tempMax: 72,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 8.0,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 1.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "5-20 dGH",
                lifespan: "4 years",
                careLevel: "Very Easy"
            },
            cardinalTetra: {
                commonName: "Cardinal Tetra",
                scientificName: "Paracheirodon axelrodi",
                tempMin: 73,
                tempMax: 84,
                tempUnit: "°F",
                phMin: 4.0,
                phMax: 7.5,
                tankSizeMin: 15,
                tankSizeUnit: "gallons",
                maxSize: 1.75,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 8+",
                waterHardness: "1-12 dGH",
                lifespan: "5 years",
                careLevel: "Easy"
            },
            rummyNoseTetra: {
                commonName: "Rummy Nose Tetra",
                scientificName: "Hemigrammus rhodostomus",
                tempMin: 72,
                tempMax: 84,
                tempUnit: "°F",
                phMin: 5.5,
                phMax: 7.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 2.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 10+",
                waterHardness: "1-8 dGH",
                lifespan: "6 years",
                careLevel: "Moderate"
            },
            emberTetra: {
                commonName: "Ember Tetra",
                scientificName: "Hyphessobrycon amandae",
                tempMin: 68,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 5.5,
                phMax: 7.5,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 0.8,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "2-10 dGH",
                lifespan: "3 years",
                careLevel: "Easy"
            },
            glowlightTetra: {
                commonName: "Glowlight Tetra",
                scientificName: "Hemigrammus erythrozonus",
                tempMin: 75,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 5.5,
                phMax: 7.5,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 1.6,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "2-15 dGH",
                lifespan: "4 years",
                careLevel: "Easy"
            },
            blackSkirtTetra: {
                commonName: "Black Skirt Tetra",
                scientificName: "Gymnocorymbus ternetzi",
                tempMin: 68,
                tempMax: 79,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 8.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 2.4,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "5-19 dGH",
                lifespan: "5 years",
                careLevel: "Easy"
            },
            cherryBarb: {
                commonName: "Cherry Barb",
                scientificName: "Puntius titteya",
                tempMin: 68,
                tempMax: 81,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 8.0,
                tankSizeMin: 15,
                tankSizeUnit: "gallons",
                maxSize: 2.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "2-20 dGH",
                lifespan: "5 years",
                careLevel: "Easy"
            },
            tigerBarb: {
                commonName: "Tiger Barb",
                scientificName: "Puntigrus tetrazona",
                tempMin: 68,
                tempMax: 79,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 3.0,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "School of 8+ minimum",
                waterHardness: "5-20 dGH",
                lifespan: "6 years",
                careLevel: "Easy"
            },
            zebraDanio: {
                commonName: "Zebra Danio",
                scientificName: "Danio rerio",
                tempMin: 64,
                tempMax: 77,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 8.0,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 2.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "5-20 dGH",
                lifespan: "4 years",
                careLevel: "Very Easy"
            },
            harlequinRasbora: {
                commonName: "Harlequin Rasbora",
                scientificName: "Trigonostigma heteromorpha",
                tempMin: 70,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 5.0,
                phMax: 7.5,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 2.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 8+",
                waterHardness: "1-12 dGH",
                lifespan: "6 years",
                careLevel: "Easy"
            },
            chiliRasbora: {
                commonName: "Chili Rasbora",
                scientificName: "Boraras brigittae",
                tempMin: 68,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 4.0,
                phMax: 7.0,
                tankSizeMin: 5,
                tankSizeUnit: "gallons",
                maxSize: 0.8,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 10+",
                waterHardness: "1-10 dGH",
                lifespan: "6 years",
                careLevel: "Moderate"
            },
            dwarfGourami: {
                commonName: "Dwarf Gourami",
                scientificName: "Trichogaster lalius",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 3.5,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "Pair or single",
                waterHardness: "2-18 dGH",
                lifespan: "4 years",
                careLevel: "Easy"
            },
            honeyGourami: {
                commonName: "Honey Gourami",
                scientificName: "Trichogaster chuna",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 2.2,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 4+",
                waterHardness: "4-15 dGH",
                lifespan: "5 years",
                careLevel: "Easy"
            },
            pearlGourami: {
                commonName: "Pearl Gourami",
                scientificName: "Trichopodus leerii",
                tempMin: 75,
                tempMax: 86,
                tempUnit: "°F",
                phMin: 5.5,
                phMax: 8.0,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 4.8,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 4+ or pair",
                waterHardness: "2-30 dGH",
                lifespan: "6 years",
                careLevel: "Easy"
            },
            sparklingGourami: {
                commonName: "Sparkling Gourami",
                scientificName: "Trichopsis pumila",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 5.0,
                phMax: 7.5,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 1.6,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 4-6",
                waterHardness: "1-12 dGH",
                lifespan: "4 years",
                careLevel: "Moderate"
            },
            germanBlueRam: {
                commonName: "German Blue Ram",
                scientificName: "Mikrogeophagus ramirezi",
                tempMin: 78,
                tempMax: 86,
                tempUnit: "°F",
                phMin: 5.0,
                phMax: 7.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 2.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Pair or small group",
                waterHardness: "1-10 dGH",
                lifespan: "3 years",
                careLevel: "Moderate"
            },
            pandaCory: {
                commonName: "Panda Cory",
                scientificName: "Corydoras panda",
                tempMin: 72,
                tempMax: 77,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.4,
                tankSizeMin: 15,
                tankSizeUnit: "gallons",
                maxSize: 2.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 6+",
                waterHardness: "1-12 dGH",
                lifespan: "10 years",
                careLevel: "Moderate"
            },
            bronzeCory: {
                commonName: "Bronze Cory",
                scientificName: "Corydoras aeneus",
                tempMin: 70,
                tempMax: 81,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 8.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 2.75,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 5+",
                waterHardness: "2-15 dGH",
                lifespan: "10 years",
                careLevel: "Easy"
            },
            pygmyCory: {
                commonName: "Pygmy Cory",
                scientificName: "Corydoras pygmaeus",
                tempMin: 72,
                tempMax: 79,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 1.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 8+",
                waterHardness: "2-10 dGH",
                lifespan: "3 years",
                careLevel: "Easy"
            },
            kuhliLoach: {
                commonName: "Kuhli Loach",
                scientificName: "Pangio kuhlii",
                tempMin: 72,
                tempMax: 79,
                tempUnit: "°F",
                phMin: 5.5,
                phMax: 7.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 4.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 5+",
                waterHardness: "0-8 dGH",
                lifespan: "10 years",
                careLevel: "Easy"
            },
            otocinclus: {
                commonName: "Otocinclus Catfish",
                scientificName: "Otocinclus spp.",
                tempMin: 70,
                tempMax: 79,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 2.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Herbivore",
                schooling: "School of 6+",
                waterHardness: "2-15 dGH",
                lifespan: "5 years",
                careLevel: "Moderate"
            },
            bristlenosePleco: {
                commonName: "Bristlenose Pleco",
                scientificName: "Ancistrus spp.",
                tempMin: 72,
                tempMax: 80,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 7.5,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 5.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Solitary",
                waterHardness: "2-20 dGH",
                lifespan: "8 years",
                careLevel: "Easy"
            },
            clownPleco: {
                commonName: "Clown Pleco",
                scientificName: "Panaqolus maccus",
                tempMin: 73,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.8,
                phMax: 7.6,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 4.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Herbivore",
                schooling: "Solitary",
                waterHardness: "3-10 dGH",
                lifespan: "10 years",
                careLevel: "Easy"
            },
            rainbowShark: {
                commonName: "Rainbow Shark",
                scientificName: "Epalzeorhynchos frenatum",
                tempMin: 72,
                tempMax: 79,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 7.5,
                tankSizeMin: 55,
                tankSizeUnit: "gallons",
                maxSize: 6.0,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "Solitary",
                waterHardness: "5-15 dGH",
                lifespan: "6 years",
                careLevel: "Moderate"
            },
            cherryShrimp: {
                commonName: "Cherry Shrimp",
                scientificName: "Neocaridina davidi",
                tempMin: 65,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 8.0,
                tankSizeMin: 5,
                tankSizeUnit: "gallons",
                maxSize: 1.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Colony of 10+",
                waterHardness: "6-14 dGH",
                lifespan: "1-2 years",
                careLevel: "Easy"
            },
            amanoShrimp: {
                commonName: "Amano Shrimp",
                scientificName: "Caridina multidentata",
                tempMin: 65,
                tempMax: 85,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 7.5,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 2.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 5+",
                waterHardness: "5-15 dGH",
                lifespan: "2-3 years",
                careLevel: "Easy"
            },
            ghostShrimp: {
                commonName: "Ghost Shrimp",
                scientificName: "Palaemonetes paludosus",
                tempMin: 65,
                tempMax: 80,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 8.0,
                tankSizeMin: 5,
                tankSizeUnit: "gallons",
                maxSize: 2.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 5+",
                waterHardness: "3-15 dGH",
                lifespan: "1-2 years",
                careLevel: "Easy"
            },
            mysterySnail: {
                commonName: "Mystery Snail",
                scientificName: "Pomacea bridgesii",
                tempMin: 68,
                tempMax: 84,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 8.4,
                tankSizeMin: 5,
                tankSizeUnit: "gallons",
                maxSize: 2.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Solitary or pairs",
                waterHardness: "8-18 dGH",
                lifespan: "1-2 years",
                careLevel: "Easy"
            },
            neriteSnail: {
                commonName: "Nerite Snail",
                scientificName: "Neritina spp.",
                tempMin: 65,
                tempMax: 85,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 8.5,
                tankSizeMin: 5,
                tankSizeUnit: "gallons",
                maxSize: 1.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Herbivore",
                schooling: "Solitary",
                waterHardness: "7-15 dGH",
                lifespan: "2 years",
                careLevel: "Easy"
            },
            
            // Additional Tetras
            blackNeonTetra: {
                commonName: "Black Neon Tetra",
                scientificName: "Hyphessobrycon herbertaxelrodi",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 5.5,
                phMax: 7.5,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 1.6,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "4-8 dGH",
                lifespan: "3-5 years",
                careLevel: "Easy"
            },
            buenosAiresTetra: {
                commonName: "Buenos Aires Tetra",
                scientificName: "Hyphessobrycon anisitsi",
                tempMin: 64,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 5.5,
                phMax: 8.5,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 3.0,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "5-20 dGH",
                lifespan: "5-6 years",
                careLevel: "Easy"
            },
            bloodfinTetra: {
                commonName: "Bloodfin Tetra",
                scientificName: "Aphyocharax anisitsi",
                tempMin: 64,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 8.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 2.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "2-30 dGH",
                lifespan: "5-10 years",
                careLevel: "Easy"
            },
            congoTetra: {
                commonName: "Congo Tetra",
                scientificName: "Phenacogrammus interruptus",
                tempMin: 73,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 3.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "3-18 dGH",
                lifespan: "3-5 years",
                careLevel: "Moderate"
            },
            lemonTetra: {
                commonName: "Lemon Tetra",
                scientificName: "Hyphessobrycon pulchripinnis",
                tempMin: 70,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 2.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "2-10 dGH",
                lifespan: "6-8 years",
                careLevel: "Easy"
            },
            serpaeTetra: {
                commonName: "Serpae Tetra",
                scientificName: "Hyphessobrycon eques",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 5.0,
                phMax: 7.8,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 1.75,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "2-15 dGH",
                lifespan: "5-7 years",
                careLevel: "Easy"
            },
            diamondTetra: {
                commonName: "Diamond Tetra",
                scientificName: "Moenkhausia pittieri",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 2.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6-8+",
                waterHardness: "2-15 dGH",
                lifespan: "3-6 years",
                careLevel: "Easy"
            },
            xRayTetra: {
                commonName: "X-Ray Tetra",
                scientificName: "Pristella maxillaris",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 15,
                tankSizeUnit: "gallons",
                maxSize: 2.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "2-15 dGH",
                lifespan: "4-5 years",
                careLevel: "Easy"
            },
            penguinTetra: {
                commonName: "Penguin Tetra",
                scientificName: "Thayeria boehlkei",
                tempMin: 73,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 5.5,
                phMax: 8.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 3.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "5-19 dGH",
                lifespan: "5-8 years",
                careLevel: "Easy"
            },
            silverDollar: {
                commonName: "Silver Dollar",
                scientificName: "Metynnis argenteus",
                tempMin: 75,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 5.0,
                phMax: 7.0,
                tankSizeMin: 55,
                tankSizeUnit: "gallons",
                maxSize: 6.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Herbivore",
                schooling: "School of 5-6+",
                waterHardness: "4-15 dGH",
                lifespan: "10+ years",
                careLevel: "Moderate"
            },
            greenNeonTetra: {
                commonName: "Green Neon Tetra",
                scientificName: "Paracheirodon simulans",
                tempMin: 76,
                tempMax: 81,
                tempUnit: "°F",
                phMin: 5.0,
                phMax: 7.0,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 1.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 10+",
                waterHardness: "0-4 dGH",
                lifespan: "3-5 years",
                careLevel: "Moderate"
            },
            
            // Additional Barbs
            rosyBarb: {
                commonName: "Rosy Barb",
                scientificName: "Pethia conchonius",
                tempMin: 61,
                tempMax: 75,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 8.0,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 4.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "5-20 dGH",
                lifespan: "5 years",
                careLevel: "Easy"
            },
            goldBarb: {
                commonName: "Gold Barb",
                scientificName: "Barbodes semifasciolatus",
                tempMin: 61,
                tempMax: 75,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 8.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 3.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "2-20 dGH",
                lifespan: "4-6 years",
                careLevel: "Very Easy"
            },
            odessaBarb: {
                commonName: "Odessa Barb",
                scientificName: "Pethia padamya",
                tempMin: 70,
                tempMax: 79,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 3.0,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "2-10 dGH",
                lifespan: "3-5 years",
                careLevel: "Easy"
            },
            denisonBarb: {
                commonName: "Denison Barb",
                scientificName: "Sahyadria denisonii",
                tempMin: 59,
                tempMax: 77,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 7.8,
                tankSizeMin: 55,
                tankSizeUnit: "gallons",
                maxSize: 6.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "5-15 dGH",
                lifespan: "5-8 years",
                careLevel: "Moderate"
            },
            fiveBandedBarb: {
                commonName: "Five-Banded Barb",
                scientificName: "Desmopuntius pentazona",
                tempMin: 70,
                tempMax: 79,
                tempUnit: "°F",
                phMin: 4.0,
                phMax: 7.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 2.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 8+",
                waterHardness: "1-5 dGH",
                lifespan: "5-8 years",
                careLevel: "Moderate"
            },
            
            // Rainbowfish (new category)
            boesemansRainbowfish: {
                commonName: "Boeseman's Rainbowfish",
                scientificName: "Melanotaenia boesemani",
                tempMin: 75,
                tempMax: 86,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 8.0,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 4.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "10-20 dGH",
                lifespan: "5-8 years",
                careLevel: "Easy"
            },
            dwarfNeonRainbowfish: {
                commonName: "Dwarf Neon Rainbowfish",
                scientificName: "Melanotaenia praecox",
                tempMin: 73,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.8,
                phMax: 7.5,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 3.2,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "5-15 dGH",
                lifespan: "5-8 years",
                careLevel: "Easy"
            },
            turquoiseRainbowfish: {
                commonName: "Turquoise Rainbowfish",
                scientificName: "Melanotaenia lacustris",
                tempMin: 68,
                tempMax: 77,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 9.0,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 4.8,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "10-20 dGH",
                lifespan: "5-8 years",
                careLevel: "Easy"
            },
            redRainbowfish: {
                commonName: "Red Rainbowfish",
                scientificName: "Glossolepis incisus",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 8.0,
                tankSizeMin: 40,
                tankSizeUnit: "gallons",
                maxSize: 6.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "10-20 dGH",
                lifespan: "5-8 years",
                careLevel: "Easy"
            },
            threadfinRainbowfish: {
                commonName: "Threadfin Rainbowfish",
                scientificName: "Iriatherina werneri",
                tempMin: 72,
                tempMax: 86,
                tempUnit: "°F",
                phMin: 5.0,
                phMax: 8.0,
                tankSizeMin: 15,
                tankSizeUnit: "gallons",
                maxSize: 1.6,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "1-12 dGH",
                lifespan: "3-4 years",
                careLevel: "Moderate"
            },
            
            // Additional Rasboras
            exclamationPointRasbora: {
                commonName: "Exclamation Point Rasbora",
                scientificName: "Boraras urophthalmoides",
                tempMin: 68,
                tempMax: 81,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.0,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 0.6,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 8-12+",
                waterHardness: "8-12 dGH",
                lifespan: "4-8 years",
                careLevel: "Moderate"
            },
            microrasbora: {
                commonName: "Green Kubotai Rasbora",
                scientificName: "Microdevario kubotai",
                tempMin: 68,
                tempMax: 81,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.0,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 0.75,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 10+",
                waterHardness: "1-10 dGH",
                lifespan: "3-5 years",
                careLevel: "Moderate"
            },
            
            // Additional Livebearers
            balloonMolly: {
                commonName: "Balloon Molly",
                scientificName: "Poecilia sphenops (balloon morph)",
                tempMin: 70,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 8.5,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 3.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 3+",
                waterHardness: "15-30 dGH",
                lifespan: "1-2 years",
                careLevel: "Easy"
            },
            variatusPlaty: {
                commonName: "Variatus Platy",
                scientificName: "Xiphophorus variatus",
                tempMin: 68,
                tempMax: 79,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 8.2,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 2.8,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 4+",
                waterHardness: "14-30 dGH",
                lifespan: "3-5 years",
                careLevel: "Easy"
            },
            blackMolly: {
                commonName: "Black Molly",
                scientificName: "Poecilia sphenops (melanistic)",
                tempMin: 70,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 8.5,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 4.8,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 4+",
                waterHardness: "15-30 dGH",
                lifespan: "3-5 years",
                careLevel: "Easy"
            },
            leastKillifish: {
                commonName: "Least Killifish",
                scientificName: "Heterandria formosa",
                tempMin: 68,
                tempMax: 78,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 8.0,
                tankSizeMin: 5,
                tankSizeUnit: "gallons",
                maxSize: 1.4,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Colony of 5+",
                waterHardness: "5-20 dGH",
                lifespan: "3-5 years",
                careLevel: "Easy"
            },
            
            // Additional Gouramis
            threeSpotGourami: {
                commonName: "Three Spot Gourami",
                scientificName: "Trichopodus trichopterus",
                tempMin: 75,
                tempMax: 86,
                tempUnit: "°F",
                phMin: 5.5,
                phMax: 8.5,
                tankSizeMin: 35,
                tankSizeUnit: "gallons",
                maxSize: 6.0,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "Single or pair",
                waterHardness: "3-35 dGH",
                lifespan: "4-6 years",
                careLevel: "Easy"
            },
            chocolateGourami: {
                commonName: "Chocolate Gourami",
                scientificName: "Sphaerichthys osphromenoides",
                tempMin: 79,
                tempMax: 88,
                tempUnit: "°F",
                phMin: 4.0,
                phMax: 6.5,
                tankSizeMin: 15,
                tankSizeUnit: "gallons",
                maxSize: 2.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Carnivore",
                schooling: "Group of 6+",
                waterHardness: "0-3 dGH",
                lifespan: "4-5 years",
                careLevel: "Difficult"
            },
            paradiseFish: {
                commonName: "Paradise Fish",
                scientificName: "Macropodus opercularis",
                tempMin: 61,
                tempMax: 79,
                tempUnit: "°F",
                phMin: 5.8,
                phMax: 8.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 4.0,
                sizeUnit: "inches",
                aggression: "Aggressive",
                diet: "Omnivore",
                schooling: "Single male only",
                waterHardness: "4-18 dGH",
                lifespan: "5-9 years",
                careLevel: "Easy"
            },
            bettaImbellis: {
                commonName: "Peaceful Betta",
                scientificName: "Betta imbellis",
                tempMin: 68,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 5.0,
                phMax: 7.5,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 2.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Carnivore",
                schooling: "Pairs or small groups",
                waterHardness: "1-10 dGH",
                lifespan: "3-5 years",
                careLevel: "Moderate"
            },
            
            // Additional Cichlids
            kribensis: {
                commonName: "Kribensis",
                scientificName: "Pelvicachromis pulcher",
                tempMin: 75,
                tempMax: 81,
                tempUnit: "°F",
                phMin: 5.0,
                phMax: 7.5,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 4.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Pairs",
                waterHardness: "0-12 dGH",
                lifespan: "5-8 years",
                careLevel: "Easy"
            },
            bolivianRam: {
                commonName: "Bolivian Ram",
                scientificName: "Mikrogeophagus altispinosus",
                tempMin: 75,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 3.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Pairs/Groups",
                waterHardness: "1-10 dGH",
                lifespan: "4-6 years",
                careLevel: "Moderate"
            },
            cockatooDwarfCichlid: {
                commonName: "Cockatoo Dwarf Cichlid",
                scientificName: "Apistogramma cacatuoides",
                tempMin: 75,
                tempMax: 84,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 3.5,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "Pairs/Harem",
                waterHardness: "2-15 dGH",
                lifespan: "3-5 years",
                careLevel: "Moderate"
            },
            electricBlueAcara: {
                commonName: "Electric Blue Acara",
                scientificName: "Andinoacara pulcher",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 7.0,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "Pairs",
                waterHardness: "4-20 dGH",
                lifespan: "8-10 years",
                careLevel: "Moderate"
            },
            firemouthCichlid: {
                commonName: "Firemouth Cichlid",
                scientificName: "Thorichthys meeki",
                tempMin: 76,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 8.0,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 6.0,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "Pairs/Groups",
                waterHardness: "5-25 dGH",
                lifespan: "10-15 years",
                careLevel: "Easy"
            },
            convictCichlid: {
                commonName: "Convict Cichlid",
                scientificName: "Amatitlania nigrofasciata",
                tempMin: 75,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 8.0,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 5.0,
                sizeUnit: "inches",
                aggression: "Aggressive",
                diet: "Omnivore",
                schooling: "Pairs",
                waterHardness: "5-25 dGH",
                lifespan: "8-10 years",
                careLevel: "Very Easy"
            },
            africanButterflyCichlid: {
                commonName: "African Butterfly Cichlid",
                scientificName: "Anomalochromis thomasi",
                tempMin: 73,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 4.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Groups",
                waterHardness: "0-12 dGH",
                lifespan: "3-5 years",
                careLevel: "Easy"
            },
            discus: {
                commonName: "Discus",
                scientificName: "Symphysodon aequifasciatus",
                tempMin: 82,
                tempMax: 86,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 55,
                tankSizeUnit: "gallons",
                maxSize: 8.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 5+",
                waterHardness: "0-12 dGH",
                lifespan: "6-10 years",
                careLevel: "Difficult"
            },
            
            // Additional Loaches
            yoyoLoach: {
                commonName: "Yoyo Loach",
                scientificName: "Botia almorhae",
                tempMin: 66,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 40,
                tankSizeUnit: "gallons",
                maxSize: 6.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 5-6+",
                waterHardness: "2-12 dGH",
                lifespan: "10-15 years",
                careLevel: "Moderate"
            },
            dwarfChainLoach: {
                commonName: "Dwarf Chain Loach",
                scientificName: "Ambastaia sidthimunki",
                tempMin: 68,
                tempMax: 77,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 2.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "2-10 dGH",
                lifespan: "8-12 years",
                careLevel: "Moderate"
            },
            zebraLoach: {
                commonName: "Zebra Loach",
                scientificName: "Botia striata",
                tempMin: 70,
                tempMax: 79,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 3.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 5-6+",
                waterHardness: "1-10 dGH",
                lifespan: "10-15 years",
                careLevel: "Moderate"
            },
            clownLoach: {
                commonName: "Clown Loach",
                scientificName: "Chromobotia macracanthus",
                tempMin: 75,
                tempMax: 86,
                tempUnit: "°F",
                phMin: 5.0,
                phMax: 7.0,
                tankSizeMin: 125,
                tankSizeUnit: "gallons",
                maxSize: 12.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 5-6+",
                waterHardness: "1-12 dGH",
                lifespan: "20+ years",
                careLevel: "Moderate"
            },
            hillstreamLoach: {
                commonName: "Hillstream Loach",
                scientificName: "Sewellia lineolata",
                tempMin: 65,
                tempMax: 75,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 2.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 4-6+",
                waterHardness: "1-10 dGH",
                lifespan: "8-12 years",
                careLevel: "Moderate"
            },
            
            // Additional Corydoras
            pepperedCory: {
                commonName: "Peppered Cory",
                scientificName: "Corydoras paleatus",
                tempMin: 60,
                tempMax: 78,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 2.8,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "3-12 dGH",
                lifespan: "10-20 years",
                careLevel: "Very Easy"
            },
            sterbaiCory: {
                commonName: "Sterbai Cory",
                scientificName: "Corydoras sterbai",
                tempMin: 73,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.6,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 2.6,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "2-15 dGH",
                lifespan: "15-20 years",
                careLevel: "Easy"
            },
            juliiCory: {
                commonName: "Julii Cory",
                scientificName: "Corydoras julii",
                tempMin: 73,
                tempMax: 79,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.8,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 2.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "2-25 dGH",
                lifespan: "10-15 years",
                careLevel: "Easy"
            },
            albinoCory: {
                commonName: "Albino Cory",
                scientificName: "Corydoras aeneus (albino)",
                tempMin: 72,
                tempMax: 80,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 2.8,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 6+",
                waterHardness: "3-10 dGH",
                lifespan: "5-10 years",
                careLevel: "Very Easy"
            },
            saltAndPepperCory: {
                commonName: "Salt and Pepper Cory",
                scientificName: "Corydoras habrosus",
                tempMin: 70,
                tempMax: 80,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 8.0,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 1.4,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "School of 8-10+",
                waterHardness: "2-25 dGH",
                lifespan: "2-5 years",
                careLevel: "Easy"
            },
            
            // Other Catfish
            chineseAlgaeEater: {
                commonName: "Chinese Algae Eater",
                scientificName: "Gyrinocheilus aymonieri",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 8.0,
                tankSizeMin: 55,
                tankSizeUnit: "gallons",
                maxSize: 11.0,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "Solitary",
                waterHardness: "4-18 dGH",
                lifespan: "10-15 years",
                careLevel: "Moderate"
            },
            stripedRaphaelCatfish: {
                commonName: "Striped Raphael Catfish",
                scientificName: "Platydoras armatulus",
                tempMin: 75,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 5.5,
                phMax: 7.5,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 9.4,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Solitary or groups",
                waterHardness: "2-20 dGH",
                lifespan: "10-15 years",
                careLevel: "Easy"
            },
            glassCatfish: {
                commonName: "Glass Catfish",
                scientificName: "Kryptopterus vitreolus",
                tempMin: 75,
                tempMax: 80,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 3.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Carnivore",
                schooling: "School of 6+",
                waterHardness: "4-12 dGH",
                lifespan: "6-8 years",
                careLevel: "Moderate"
            },
            upsideDownCatfish: {
                commonName: "Upside-Down Catfish",
                scientificName: "Synodontis nigriventris",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.0,
                phMax: 7.5,
                tankSizeMin: 30,
                tankSizeUnit: "gallons",
                maxSize: 4.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Group of 3-5+",
                waterHardness: "5-20 dGH",
                lifespan: "15+ years",
                careLevel: "Easy"
            },
            commonPleco: {
                commonName: "Common Pleco",
                scientificName: "Hypostomus plecostomus",
                tempMin: 72,
                tempMax: 86,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 7.8,
                tankSizeMin: 75,
                tankSizeUnit: "gallons",
                maxSize: 24.0,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "Solitary",
                waterHardness: "2-12 dGH",
                lifespan: "10-15 years",
                careLevel: "Moderate"
            },
            rubberLipPleco: {
                commonName: "Rubber Lip Pleco",
                scientificName: "Chaetostoma milesi",
                tempMin: 72,
                tempMax: 78,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 8.0,
                tankSizeMin: 25,
                tankSizeUnit: "gallons",
                maxSize: 7.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Herbivore",
                schooling: "Solitary",
                waterHardness: "8-12 dGH",
                lifespan: "10-15 years",
                careLevel: "Easy"
            },
            
            // Additional Shrimp
            bambooShrimp: {
                commonName: "Bamboo Shrimp",
                scientificName: "Atyopsis moluccensis",
                tempMin: 70,
                tempMax: 78,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 7.8,
                tankSizeMin: 20,
                tankSizeUnit: "gallons",
                maxSize: 3.0,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Solitary or groups",
                waterHardness: "6-18 dGH",
                lifespan: "1-2 years",
                careLevel: "Moderate"
            },
            singaporeShrimp: {
                commonName: "Singapore Shrimp",
                scientificName: "Macrobrachium lanchesteri",
                tempMin: 70,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 7.5,
                tankSizeMin: 15,
                tankSizeUnit: "gallons",
                maxSize: 4.0,
                sizeUnit: "inches",
                aggression: "Semi-aggressive",
                diet: "Omnivore",
                schooling: "Colony of 5+",
                waterHardness: "5-15 dGH",
                lifespan: "2-3 years",
                careLevel: "Moderate"
            },
            
            // Additional Snails
            ramshornSnail: {
                commonName: "Ramshorn Snail",
                scientificName: "Planorbidae family",
                tempMin: 60,
                tempMax: 80,
                tempUnit: "°F",
                phMin: 7.0,
                phMax: 8.0,
                tankSizeMin: 5,
                tankSizeUnit: "gallons",
                maxSize: 1.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Omnivore",
                schooling: "Solitary or colony",
                waterHardness: "8-15 dGH",
                lifespan: "1-3 years",
                careLevel: "Very Easy"
            },
            
            // Amphibians
            africanDwarfFrog: {
                commonName: "African Dwarf Frog",
                scientificName: "Hymenochirus boettgeri",
                tempMin: 72,
                tempMax: 82,
                tempUnit: "°F",
                phMin: 6.5,
                phMax: 7.8,
                tankSizeMin: 10,
                tankSizeUnit: "gallons",
                maxSize: 2.5,
                sizeUnit: "inches",
                aggression: "Peaceful",
                diet: "Carnivore",
                schooling: "Colony of 2+",
                waterHardness: "5-12 dGH",
                lifespan: "5-10 years",
                careLevel: "Easy"
            }
        };
