/**
 * Plant Database
 * Aquarium plant data for the glossary
 */

var plantDatabase = {
  javaFern: {
    commonName: 'Java Fern',
    scientificName: 'Microsorum pteropus',
    origin: 'asia',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2FjavaFern.jpg?alt=media',
    position: 'midground',
    plantingStyle: 'attachToWood',
    difficulty: 'Easy',
    lightNeeds: 'Low to Medium',
    tempMin: 68,
    tempMax: 82,
    tempUnit: '°F',
    phMin: 6.0,
    phMax: 7.5,
    growthRate: 'Slow',
    maxHeight: '8-14',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Rhizome division, adventitious plantlets',
  },

  javaMoss: {
    commonName: 'Java Moss',
    scientificName: 'Taxiphyllum barbieri',
    origin: 'asia',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2FjavaMoss.jpg?alt=media',
    position: 'foreground',
    plantingStyle: 'attachToWood',
    difficulty: 'Easy',
    lightNeeds: 'Low',
    tempMin: 59,
    tempMax: 82,
    tempUnit: '°F',
    phMin: 5.5,
    phMax: 8.0,
    growthRate: 'Slow to Moderate',
    maxHeight: '2-4',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Division, fragmentation',
  },

  amazonSword: {
    commonName: 'Amazon Sword',
    scientificName: 'Echinodorus amazonicus',
    origin: 'southAmerica',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2FamazonSword.jpg?alt=media',
    position: 'background',
    plantingStyle: 'substrate',
    difficulty: 'Easy',
    lightNeeds: 'Medium',
    tempMin: 72,
    tempMax: 82,
    tempUnit: '°F',
    phMin: 6.5,
    phMax: 7.5,
    growthRate: 'Moderate',
    maxHeight: '12-20',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Runners, adventitious plantlets',
  },

  anubias: {
    commonName: 'Anubias',
    scientificName: 'Anubias barteri',
    origin: 'africa',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2Fanubias.jpg?alt=media',
    position: 'foreground',
    plantingStyle: 'attachToWood',
    difficulty: 'Easy',
    lightNeeds: 'Low to Medium',
    tempMin: 72,
    tempMax: 82,
    tempUnit: '°F',
    phMin: 6.0,
    phMax: 7.5,
    growthRate: 'Slow',
    maxHeight: '4-16',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Rhizome division',
  },

  vallisneria: {
    commonName: 'Vallisneria',
    scientificName: 'Vallisneria spiralis',
    origin: 'asia',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2Fvallisneria.jpg?alt=media',
    position: 'background',
    plantingStyle: 'substrate',
    difficulty: 'Easy',
    lightNeeds: 'Medium',
    tempMin: 68,
    tempMax: 82,
    tempUnit: '°F',
    phMin: 6.5,
    phMax: 8.5,
    growthRate: 'Fast',
    maxHeight: '12-24',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Runners',
  },

  cryptocoryne: {
    commonName: 'Cryptocoryne',
    scientificName: 'Cryptocoryne wendtii',
    origin: 'asia',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2Fcryptocoryne.jpg?alt=media',
    position: 'midground',
    plantingStyle: 'substrate',
    difficulty: 'Easy',
    lightNeeds: 'Low to Medium',
    tempMin: 72,
    tempMax: 82,
    tempUnit: '°F',
    phMin: 6.0,
    phMax: 8.0,
    growthRate: 'Slow',
    maxHeight: '4-8',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Runners, division',
  },

  dwarfSagittaria: {
    commonName: 'Dwarf Sagittaria',
    scientificName: 'Sagittaria subulata',
    origin: 'northCentralAmerica',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2FdwarfSagittaria.jpg?alt=media',
    position: 'foreground',
    plantingStyle: 'substrate',
    difficulty: 'Easy',
    lightNeeds: 'Medium',
    tempMin: 68,
    tempMax: 82,
    tempUnit: '°F',
    phMin: 6.0,
    phMax: 8.0,
    growthRate: 'Moderate to Fast',
    maxHeight: '4-12',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Runners',
  },

  hornwort: {
    commonName: 'Hornwort',
    scientificName: 'Ceratophyllum demersum',
    origin: 'northCentralAmerica',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2Fhornwort.jpg?alt=media',
    position: 'background',
    plantingStyle: 'floating',
    difficulty: 'Easy',
    lightNeeds: 'Medium',
    tempMin: 59,
    tempMax: 86,
    tempUnit: '°F',
    phMin: 6.0,
    phMax: 7.5,
    growthRate: 'Fast',
    maxHeight: '24-120',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Fragmentation, side shoots',
  },

  waterWisteria: {
    commonName: 'Water Wisteria',
    scientificName: 'Hygrophila difformis',
    origin: 'asia',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2FwaterWisteria.jpg?alt=media',
    position: 'midground',
    plantingStyle: 'substrate',
    difficulty: 'Easy',
    lightNeeds: 'Medium to High',
    tempMin: 74,
    tempMax: 82,
    tempUnit: '°F',
    phMin: 6.5,
    phMax: 7.5,
    growthRate: 'Fast',
    maxHeight: '12-20',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Cuttings, side shoots',
  },

  duckweed: {
    commonName: 'Duckweed',
    scientificName: 'Lemna minor',
    origin: 'northCentralAmerica',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2Fduckweed.jpg?alt=media',
    position: 'surface',
    plantingStyle: 'floating',
    difficulty: 'Easy',
    lightNeeds: 'Low to High',
    tempMin: 50,
    tempMax: 86,
    tempUnit: '°F',
    phMin: 5.0,
    phMax: 9.0,
    growthRate: 'Very Fast',
    maxHeight: '0.1-0.3',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Division, budding',
  },

  amazonFrogbit: {
    commonName: 'Amazon Frogbit',
    scientificName: 'Limnobium laevigatum',
    origin: 'southAmerica',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2FamazonFrogbit.jpg?alt=media',
    position: 'surface',
    plantingStyle: 'floating',
    difficulty: 'Easy',
    lightNeeds: 'Medium to High',
    tempMin: 64,
    tempMax: 84,
    tempUnit: '°F',
    phMin: 6.0,
    phMax: 7.5,
    growthRate: 'Fast',
    maxHeight: '1-2',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Runners, daughter plants',
  },

  marimo: {
    commonName: 'Marimo Moss Ball',
    scientificName: 'Aegagropila linnaei',
    origin: 'asia',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2Fmarimo.jpg?alt=media',
    position: 'foreground',
    plantingStyle: 'substrate',
    difficulty: 'Easy',
    lightNeeds: 'Low',
    tempMin: 59,
    tempMax: 77,
    tempUnit: '°F',
    phMin: 6.0,
    phMax: 8.0,
    growthRate: 'Very Slow',
    maxHeight: '2-5',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Division',
  },

  bacopa: {
    commonName: 'Bacopa',
    scientificName: 'Bacopa caroliniana',
    origin: 'northCentralAmerica',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2Fbacopa.jpg?alt=media',
    position: 'midground',
    plantingStyle: 'substrate',
    difficulty: 'Moderate',
    lightNeeds: 'Medium to High',
    tempMin: 68,
    tempMax: 82,
    tempUnit: '°F',
    phMin: 6.0,
    phMax: 7.5,
    growthRate: 'Moderate',
    maxHeight: '6-12',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Cuttings, side shoots',
  },

  rotala: {
    commonName: 'Rotala',
    scientificName: 'Rotala rotundifolia',
    origin: 'asia',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2Frotala.jpg?alt=media',
    position: 'background',
    plantingStyle: 'substrate',
    difficulty: 'Moderate',
    lightNeeds: 'Medium to High',
    tempMin: 68,
    tempMax: 82,
    tempUnit: '°F',
    phMin: 5.5,
    phMax: 7.5,
    growthRate: 'Fast',
    maxHeight: '8-24',
    heightUnit: 'inches',
    co2Required: false,
    propagation: 'Cuttings, side shoots',
  },

  dwarfHairgrass: {
    commonName: 'Dwarf Hairgrass',
    scientificName: 'Eleocharis parvula',
    origin: 'northCentralAmerica',
    imageUrl:
      'https://firebasestorage.googleapis.com/v0/b/comparium-21b69.firebasestorage.app/o/images%2Fplants%2FdwarfHairgrass.jpg?alt=media',
    position: 'foreground',
    plantingStyle: 'substrate',
    difficulty: 'Moderate',
    lightNeeds: 'High',
    tempMin: 68,
    tempMax: 82,
    tempUnit: '°F',
    phMin: 6.0,
    phMax: 7.5,
    growthRate: 'Moderate',
    maxHeight: '2-6',
    heightUnit: 'inches',
    co2Required: true,
    propagation: 'Runners',
  },
};
